In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])
a2=np.array([[1,2],[3,4]])
a3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])#2-D
a4=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]]])#4-D

In [3]:
a4.shape

(2, 2, 2, 2)

In [4]:
h1=np.array([1,2,3,4,0],dtype=bool)#bool ,int,float
h1

array([ True,  True,  True,  True, False])

In [5]:
k=np.arange(1,10,2)#like range
k1=np.arange(1,12,2).reshape(2,3) #must allign witrh no of elements
k1

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [6]:
k=np.ones((3,4))
k=np.zeros((2,2))
k

array([[0., 0.],
       [0., 0.]])

In [7]:
k=np.random.random((3,3))#generate float integers 0 to 1 range
k1=np.random.randint(2,9,size=(2,2))
k2=np.linspace(10,100,10)#floating number
k2

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [8]:
np.identity(2)#generate identity matrix

array([[1., 0.],
       [0., 1.]])

In [9]:
a4.ndim #tell no of dimensions in int 4-D = 4
a4.size #gives you total no of items irespective of dimensions
a1.itemsize#size in bytes

4

In [10]:
h1.dtype
h1.astype(np.int32)#change data type
a1.astype(np.int8)
a1.itemsize

4

In [11]:
a1*2
a1+2
a1**2
a1/2

array([0.5, 1. , 1.5])

In [12]:
#gives bool value
a1==15 
a1>1

array([False,  True,  True])

In [13]:
ar1=np.arange(0,10).reshape(2,5)
ar2=np.arange(11,21).reshape(2,5)
ar=ar1*ar2
ar1+ar2
ar

array([[  0,  12,  26,  42,  60],
       [ 80, 102, 126, 152, 180]])

In [14]:
np.max(ar)
np.min(ar)
np.max(ar,axis=0)#axis=0 column wise , axis=1 rowwise
np.mean(ar)
np.median(ar,axis=1) #std ,var
np.sin(ar) #cos tan

array([[ 0.        , -0.53657292,  0.76255845, -0.91652155, -0.30481062],
       [-0.99388865,  0.99482679,  0.32999083,  0.93332052, -0.80115264]])

In [15]:
k=np.arange(0,10).reshape(2,5)
k1=np.arange(0,10).reshape(5,2)
np.dot(k,k1)

array([[ 60,  70],
       [160, 195]])

In [16]:
np.log(k)
np.exp(k)#exponent

C:\Users\HP\AppData\Local\Temp\ipykernel_16292\2481232914.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(k)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [17]:
print(a1,'\n',a2,'\n\n\n',a3)

[1 2 3] 
 [[1 2]
 [3 4]] 


 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [98]:
ar3=np.arange(1,76).reshape(3,5,5)
a1[1]
a1[1:2]
a2[1,1]#row,column
a3[1,1,1]#which 2-d ,row,column
ar3


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]],

       [[51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60],
        [61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75]]])

In [19]:
ar3[[0,1],[[0,3],[1,2]],:]#advanced fancy indexing mixing results
ar3[0,[0,3],:]
ar3[[0,1],0:3:2,:]#

array([[[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]],

       [[26, 27, 28, 29, 30],
        [36, 37, 38, 39, 40]]])

In [20]:
for i in ar3:
    print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[[51 52 53 54 55]
 [56 57 58 59 60]
 [61 62 63 64 65]
 [66 67 68 69 70]
 [71 72 73 74 75]]


In [21]:
np.transpose(ar3[0])#ao also apply on ar3
ar1=np.transpose(ar3[0,[0,1],:])#ao also apply on ar3
ar1

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [22]:
np.nditer(ar3)#iterable object
ar3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75])

In [23]:
ar2=np.arange(1,11).reshape(5,2)
ar4=np.arange(1,5).reshape(2,2)
k1=np.hstack((ar1,ar2))
k2=np.vstack((ar1,ar4))

In [24]:
np.hsplit(k2,2) #column vise split even number of columns

[array([[1],
        [2],
        [3],
        [4],
        [5],
        [1],
        [3]]),
 array([[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [ 2],
        [ 4]])]

In [ ]:
np.vsplit(k2,2) #error because it must be qual division even number of rows 

In [26]:
import time
import sys
time.time()
time.perf_counter()
sys.getsizeof(ar3)

144

In [27]:
ar3=ar3.astype(np.int16)

In [28]:
ar3[ar3>50] #it gives all those element in 1 D array who is greater then 50 ar3>50 give boolean series which work as mask
#a%2 ((a>50) & (a%2))
ar3[~((ar3>50) | (ar3%2==0))] # | : or & : and ~ : not 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49], dtype=int16)

In [33]:
a1=np.array([11,2,3,np.nan,5])
a1[~np.isnan(a1)]

array([11.,  2.,  3.,  5.])

In [43]:
np.sort(ar3)[::-1]
np.sort(ar3[2][1])[::-1]#reverse sorting
np.sort(ar3[0],axis=1)[::-1]#reverse sorting

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]], dtype=int16)

In [51]:
np.append(a1,100)
np.append(ar3,100)#convert it to one -D then append
np.append(ar3[0],np.ones((ar3[0].shape[0],1)),axis=1)#column wise

array([[ 1.,  2.,  3.,  4.,  5.,  1.],
       [ 6.,  7.,  8.,  9., 10.,  1.],
       [11., 12., 13., 14., 15.,  1.],
       [16., 17., 18., 19., 20.,  1.],
       [21., 22., 23., 24., 25.,  1.]])

In [53]:
np.concatenate((ar3[0],ar3[1]),axis=1)#can used as replacement of stack
np.concatenate((ar3[0],ar3[1]),axis=0)#can used as replacement of stack


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]], dtype=int16)

In [54]:
np.unique(ar3)#give one-D array of unique element

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75], dtype=int16)

In [59]:
l1=np.expand_dims(ar3[0],axis=0)
l2=np.expand_dims(ar3[0],axis=1)
l1.shape
l2.shape
l2

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25]]], dtype=int16)

In [62]:
ind=np.where(ar3>50)
ar3[ind]
ind

(array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2], dtype=int64),
 array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
        2, 3, 4], dtype=int64))

In [70]:
np.where(ar3[2]>50,1,0)#condition,True,False


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [77]:
np.argmax(ar3)#convert it to 1-D then give index position
np.argmin(ar3)
np.argmin(ar3[0],axis=0)#row wise columnwise index position

array([0, 0, 0, 0, 0], dtype=int64)

In [83]:
np.cumsum(ar3)
np.cumsum(ar3,axis=1)#cumprod
np.percentile(ar3[0],75)#0=mininmum  100=maximum  


19.0

In [85]:
np.histogram(ar3[0],bins=[0,7,13,25])

(array([ 6,  6, 13], dtype=int64), array([ 0,  7, 13, 25]))

In [86]:
#np.corrcoef()  correlation of two quantity
np.corrcoef(ar3[0],ar3[1])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [89]:
np.isin(ar3[0],[26,27,16]) # give boolean expression can be used as mask

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [107]:
np.flip(ar3)
np.flip(ar3,axis=1)
np.delete(ar3,[0,1],axis=1)#used for deletion
np.put(ar3,[np.argmin(ar3),np.argmax(ar3)],[-10,300])#permanent change replace elements traet whole array as 1-D irrespective of dimentions can be worked with argmin argmax
ind=ar3.ravel()
np.put(ar3,[np.where(ind>50)],[300])
ar3

array([[[-10,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25]],

       [[ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[300, 300, 300, 300, 300],
        [300, 300, 300, 300, 300],
        [300, 300, 300, 300, 300],
        [300, 300, 300, 300, 300],
        [300, 300, 300, 300, 300]]])

In [105]:
np.intersect1d(ar3[0],ar3[1])
np.union1d(ar3[0],ar3[1])
np.setdiff1d(ar3[0],ar3[1])
np.setxor1d(ar3[0],ar3[1])#work as union if both has different numbers else it elminate common number 
np.in1d(ar3[0],ar3[1])#check element of ar3[0] is present in ar3[1] can be used as mask return boolean series

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [106]:
np.clip(ar3[0],0,19)

array([[ 0,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 19],
       [19, 19, 19, 19, 19]])